name: hands_on_ppml_visum
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9.*
  - conda-lock
  - mamba
  - pip  # pip must be mentioned explicitly, or conda-lock will fail
  - poetry=1.*
  - cpuonly
  - pytorch::pytorch=1.11.0
  - pytorch::torchvision=0.12.0
  - opacus=1.1.2

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64

